CREATE DATABASE IF NOT EXISTS indy_bot_db;

USE indy_bot_db;

CREATE USER IF NOT EXISTS 'bot'@'localhost' IDENTIFIED BY 'indy_pass';
GRANT ALL PRIVILEGES ON indy_bot_db.* TO 'bot'@'localhost';

CREATE TABLE users (
   id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   discord_id BIGINT UNSIGNED UNIQUE NOT NULL,

   whereis_enabled BOOLEAN NOT NULL DEFAULT FALSE,
   whereis_visibility ENUM('Group', 'Server') NOT NULL DEFAULT 'Group',

   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE credentials (
   user_id BIGINT UNSIGNED PRIMARY KEY,

   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,

   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

   FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE guilds (
   id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   discord_id BIGINT UNSIGNED UNIQUE NOT NULL,

   timezone VARCHAR(64) NOT NULL DEFAULT "Europe/Vienna",

   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE guild_features (
   guild_id BIGINT UNSIGNED NOT NULL,
   feature VARCHAR(64) NOT NULL,
   enabled BOOLEAN NOT NULL DEFAULT TRUE,

   PRIMARY KEY(guild_id, feature),
   FOREIGN KEY(guild_id) REFERENCES guilds(id) ON DELETE CASCADE
);
