CREATE DATABASE IF NOT EXISTS indy_bot_db;

USE indy_bot_db;

CREATE USER IF NOT EXISTS 'bot'@'localhost' IDENTIFIED BY 'indy_pass';
GRANT ALL PRIVILEGES ON indy_bot_db.* TO 'bot'@'localhost';

CREATE TABLE users (
   id UNSIGNED BIGINT PRIMARY KEY AUTO_INCREMENT,
   discord_id UNSIGNED BIGINT UNIQUE NOT NULL,

   whereis_enabled BOOLEAN NOT NULL DEFAULT FALSE,
   whereis_visibility ENUM('Group', 'Server') NOT NULL DEFAULT 'Group',

   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE credentials (
   user_id UNSIGNED BIGINT PRIMARY KEY,

   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,

   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

   FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
